name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Config
        run: sudo apt update
      - name: Rust
        run: sudo apt install cargo
      - name: Env
        run: sudo apt install libpcap-dev
      - name: Build
        run: sudo cargo build --verbose
      - name: Tests
        run: sudo cargo test --verbose
